language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t hayeonkimm/docker-team -f ./Dockerfile

branches:
  only:
    - hayeon
notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - hayeon.data@gmail.com


script:
  - docker run -e CI=true hayeonkimm/docker-team npm ru ntest

after_success:
  - docker build -t hayeonkimm/docker-team ./
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push hayeonkimm/docker-team
