version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3001:80'
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    container_name: app_backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db/
    ports:
      - '27017:27017'

volumes:
  mongo:
