version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx

    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app

    ports: -"3001:80"

  backend:
