version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./final_teamnote/node_modules
      - ./:/app
    container_name: app_backend
    ports:
      - 3001:3001

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db/
    ports:
      - '27017:27017'

volumes:
  mongo:
