version: "3"

services:
  final_project:
    build:
      context: .
    ports:
    - 3000:3001
  nginx:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3000:80